### ISSUE TITLE
Question library seems to cut some cards in half

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-js#1051]
![screen shot 2016-05-02 at 3 39 24 pm](https://cloud.githubusercontent.com/assets/1017808/14969261/eaeb693c-1086-11e6-88d4-c9cac0d23605.png)

**Comment by nathanstitt** [comment]
Yeah, we've got a pivotal ticket on this https://www.pivotaltracker.com/story/show/118590241  It's a simple style fix, but aren't doing it until UX decides whether the column style will stick around or not.

**Comment by Dantemss** [comment]
Closing this since it's a duplicate.
