### ISSUE TITLE
Accessibility: User can tab through paragraphs

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor-js#2375]
# Description
Allow user to tab through paragraphs in the reading with Chrome plugin. Verify that this is a bug, and that we need to use Chrome box. Report back with correct keys. 

#Acceptance
User can tab through paragraphs

**Comment by nathanstitt** [comment]
in order for this to work, I think we'll have to change the paragraphs to be sections, which seems incorrect from a semantic standpoint.

Not sure if this should even be a thing?

**Comment by carlycurran** [comment]
There is a built in way to move between sections. In our books, headers are the sections. 

Per Ed and accessibility team, users do not tab through paragraphs. They did not hear this need at conference. We should NOT retag paragraphs as sections. (In a related card, Nathan did retag answer choices as sections.) We do put IDs on paragraphs.

Users can also tab through content "chunk by chunk" using arrow keys. We also have elements in place that allow users to tab through.

Does this work with NVDA? Does Tom have additional info?

**Comment by Malar-Natarajan** [comment]
Tabbed through paragraphs using chromevox+arrow keys in qa
