### ISSUE TITLE
Bug: View in book icon in Highlight summary page works incorrectly for images

### ISSUE THREAD

**Issue by TomWoodward** [openstax/tutor-js#2377]
**SCENARIO** _View in book icon in Highlight summary page works incorrectly for images
----------------
**Steps to Reproduce the issue:** _
Highlight an image
From the Highlights SUmmary page, click on the 'View in book' icon
User is taken to the top of the page in which image is present and not to the image location

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [X] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
Images don't have text content; and current implementation of highlighting doesn't support things that don't have text in them. Tom talking to Phil about ways to serialize content. 

Possibility: take browser range objects, which represent highlight, and serialize it with query selectors for start and end container of the range.

**Comment by carlycurran** [comment]
Deployed to -dev so @Malar-Natarajan  can take a look at this.

**Comment by Malar-Natarajan** [comment]
Verified in QA
