### ISSUE TITLE
Bug: The pop-up to help new users regarding highlighting is incorrectly positioned

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor-js#2380]
![Screen Shot 2018-10-02 at 12.42.16 PM.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/c40dfb94-7acb-4114-bef7-7ce1d4c66956)

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Malar-Natarajan** [comment]
Staging did not show the popup. COuld be staging specific issue.
