### ISSUE TITLE
Automated User Errors reported to CS

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/tutor-js#2418]
List of all User Errors Automated as well as reported to CS!

P.S. Add user errors in comments along with the case#

**Comment by meeragovindaraju** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/course/4467/practice/1756140 while using browser 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36.

The request details are: 
PUT on https://tutor.openstax.org/api/steps/17930950/completed returned status "422" with message "Unprocessable Entity"

The request body was: 
{"free_response":"g","answer_id":"319563"}.

Case#28279

**Comment by nathanstitt** [comment]
Thanks Meera.

I think this probably happened right as the deployment was occurring last night while Tutor was in a partial down status.  Do let us know if you get anymore though since it should have been completed by around 11pm

Nathan


On November 8, 2018 at 9:25:56 AM, meeragovindaraju (notifications@github.com) wrote:

I ran into a problem at https://tutor.openstax.org/course/4576/task/1709875/step/10 while using browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134.

The request details are:

PATCH on https://tutor.openstax.org/api/steps/17083805 returned status "502" with message "Bad Gateway"

The request body was:

{"answer_id":"256842"}.

Case #28320

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/4749/homework/new?due_at=2018-11-17# while using browser

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36.
The request details are:

POST on https://tutor.openstax.org/api/courses/4749/plans returned status "422" with message "Unprocessable Entity"

The request body was:

{"type":"homework","is_feedback_immediate":true,"settings":{"page_ids":["26529","26530","26531","26532"],"exercise_ids":["327618","327612","327648","327647","327632","327646","327629","327621","327620","327619","327655","327654","327684","327666","327663","327660","327689","327659","327667","327665"],"exercises_count_dynamic":0},"tasking_plans":[{"target_type":"period","target_id":"6863","opens_at":"2018-11-11 00:01","due_at":"2018-11-26 23:59"}],"title":"Week 1 Openstax Tutor Quiz - Chapter 1, 2 ","is_publish_requested":true}.

Case #28348

**Comment by nathanstitt** [comment]
Looks like ^^^ was probably due to course dates not being set correctly

**Comment by bonnebbrown** [comment]
I ran into a problem at https://tutor.openstax.org/course/4804/task/1832180/step/4 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36.

The request details are:
undefinedThe request body was:
{"error": "TypeError: Cannot read property 'is_completed' of null"}.
Case #30132

**Comment by bonnebbrown** [comment]
I ran into a problem at https://tutor.openstax.org/course/4901/task/1809940 while using browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36.

The request details are: undefined on undefined returned status "0" with message "TypeError Cannot read property 'headers' of undefined"

Case #30217

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4967/task/1857963/step/2 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36. The request details are: undefinedThe request body was: { "error": "TypeError: Cannot read property 'id' of undefined" }.
Case # 30532

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4804/task/1837363/step/2 while using browserMozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15.
The request details are:
put on https://tutor.openstax.org/api/steps/19598446/completed returned status "422" with message "Unprocessable Entity"
The request body was:
{}.
Case #30604

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/4920/task/1820327/step/2 while using browser Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36.
The request details are:
undefinedThe request body was:
{"error": "TypeError: Cannot read property 'id' of undefined"}.
Case #30702

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/dashboard while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15. The request details are: undefinedThe request body was: {"error": "TypeError: undefined is not an object (evaluating 'l.id')"}.

Case # 30738

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/4804/task/1855101/step/2 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15. The request details are: undefinedThe request body was: {"error": "TypeError: undefined is not an object (evaluating 'l.id')"}.

Case #30777, course 4804

**Comment by osiris001** [comment]
Hello!

  I ran into a problem at https://tutor.openstax.org/course/4804/task/1841848/step/2 while using browser
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15.

The request details are:
undefinedThe request body was:
{
  "error": "TypeError: undefined is not an object (evaluating 'l.id')"
}.

I have tried in both google chrome and safari browsers. My account is under the email jillianmmack@ku.edu

Case #30830 Course:4804

**Comment by osiris001** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/course/4804?tab=0 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36.

The request details are:
undefinedThe request body was:
{
"error": "TypeError: Cannot read property 'id' of undefined"
}.

Case #30833 , Course 4804

**Comment by osiris001** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/course/4804/task/1836926/step/2 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15.

The request details are:
undefinedThe request body was:
{
"error": "TypeError: undefined is not an object (evaluating 'l.id')"

case 30845, course: 4804

**Comment by osiris001** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/course/4804/task/1839715/step/2 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36.

The request details are:
undefinedThe request body was:
{
"error": "TypeError: Cannot read property 'id' of undefined"

case: 30847, course: 4804

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4896/task/1795095/step/8 while using browser Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/72.0.3626.101 Mobile/15E148 Safari/605.1.
The request details are:
undefinedThe request body was:{"error": "TypeError: null is not an object (evaluating 'e.is_completed')"}.
 case 30930, course 4896

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4920/task/1820327/step/2 while using browser Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36.  The request details are: undefinedThe request body was: {   "error": "TypeError: Cannot read property 'id' of undefined" }.
Case 3056, course 4920

**Comment by bonnebbrown** [comment]
I ran into a problem at https://tutor.openstax.org/book/159 while using browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063. The request details are: undefinedThe request body was: {  "error": "TypeError: Object doesn't support property or method 'forEach'"}.
Case 30964, course 5067, using Microsoft edge 40.15063.674.0 

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://tutor.openstax.org/book/159">OpenStax Accounts</a></strong></div></blockquote>

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4893/task/1917859/step/11 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36.
The request details are:
put on https://tutor.openstax.org/api/steps/21307490/completed returned status "422" with message "Unprocessable Entity"
The request body was: {"free_response":"lower\n","answer_id":"241556"}.

Case 31056, course 4893

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4958/task/1928617/step/46 while using browser Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/73.0.3683.68 Mobile/15E148 Safari/605.1. The request details are: undefined on undefined returned status "0" with message "No response was received.”
Case 31370, course 4958

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/4920/task/1811201/step/19 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15.
The request details are: undefinedThe request body was: {"error": "TypeError: null is not an object (evaluating 'e.is_completed')"
Case 31464, course 4920

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/5067/task/1915828/step/31 while using browser Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36. The request details are: undefinedThe request body was: {  "error": "TypeError: Cannot read property 'is_completed' of null"}.

Case #31642, course 5067

**Comment by bonnebbrown** [comment]
I ran into a problem at https://tutor.openstax.org/course/4804/task/1835266/step/6 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15.
The request details are:
patch on https://tutor.openstax.org/api/steps/19557105 returned status “422” with message “Unprocessable Entity”
The request body was:
{“is_completed”:true,“answer_id”:“213489”,“free_response”:” “,”response_validation”:{}}.
Case 32371

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4804/task/1835268/step/8 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15.
The request details are:
patch on https://tutor.openstax.org/api/steps/19557167 returned status "422" with message "Unprocessable Entity"

The request body was:
{"is_completed":true,"answer_id":"220484","free_response":" ","response_validation":{}}.
Case 00032428, course 4804

**Comment by khannum19** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/4756/t/month/2019-04-02 while using browser  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36.

The request details are:
get on https://tutor.openstax.org/api/plans/44343/stats returned status "502" with message "Bad Gateway"

Note from Instructor: This reading assignment appears to no longer be working and has disappeared from student scores.  What should I do?

Case 00032482, Course 4756

**Comment by khannum19** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/book/159 while using browser
Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1.

The request details are:
undefinedThe request body was:
{
"error": "Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build."
}.

Case 3248485

Note: Unclear who user is. Could not find the name or email attached to Salesforce or Accounts (OS/Tutor).

**Comment by khannum19** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/book/160 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36.

The request details are:
undefinedThe request body was:
{
"error": "Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build."
}.

**Comment by khannum19** [comment]
Hello!

 

  I ran into a problem at https://tutor.openstax.org/book/160 while using browser

 

  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36.

 

The request details are:

 

undefinedThe request body was:

 

{  "error": "Error: [mobx] An invariant failed, however the error is obfuscated because this is an production build."}.

Case 00032501

**Comment by osiris001** [comment]
Hello!

  I ran into a problem at https://tutor.openstax.org/course/4804/task/1872849/step/1 while using browser
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36.

The request details are:
undefinedThe request body was:
{
  "error": "TypeError: Cannot read property 'isPlaceHolder' of undefined"
}.
case: 32658

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/4899/t/month/2019-11-01 while using browser Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36.

The request details are: undefinedThe request body was: {"error": "TypeError: Cannot destructure property `offsets` of 'undefined' or 'null'."}.

Case 32895, course 4899

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/course/5361 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36.

The request details are:
put on https://tutor.openstax.org/api/terms/7,6 returned status "503" with message "Service Unavailable: Back-end server is at capacity"
Case 33535, course 5361, time of report 12:39pm

**Comment by bonnebbrown** [comment]
Hello! I ran into a problem at https://tutor.openstax.org/course/5234/task/1971025/step/4 while using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15.

The request details are:
post on https://tutor.openstax.org/api/courses/5234/notes/44.1 returned status "503" with message "Service Unavailable: Back-end server is at capacity"

The request body was:
{"anchor":"#32deb145-a903-44d6-8d1e-45adff7d0946","contents":{"title":"The Scope of Ecology","rect":{"bottom":4513,"top":4492,"left":505.27734375,"right":608.232421875},"content":"Mutualism","id":"1559779892912","endContainer":"./*[name()='section'][4]/*[name()='p'][2]/*[name()='span'][1]/text()[1]","endOffset":9,"referenceElementId":"32deb145-a903-44d6-8d1e-45adff7d0946","startContainer":"./*[name()='section'][4]/*[name()='p'][2]/*[name()='span'][1]/text()[1]","startOffset":0,"type":"XpathRangeSelector"},"annotation":""}.
case #33553, course 5234, time 7:13 pm

**Comment by bonnebbrown** [comment]
Hello!
I ran into a problem at https://tutor.openstax.org/book/5234/page/30221 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15.

The request details are:
put on https://tutor.openstax.org/api/user/ui_settings returned status "504" with message "No response was received"

The request body was:
{"ui_settings":{"sessionCount":33,"has-viewed-individual-review-intro":{"taskId":"1966765"},"has-viewed-personalized-intro":{"taskId":"1966766"},"has-viewed-two-step-intro":{"taskId":"1966766"},"has-viewed-spaced-practice-intro":{"taskId":"1966766"},"is_scores_averages_expanded":false}}.
case 33554, course 5234, time 7:13pm

**Comment by bonnebbrown** [comment]
Hello!

I ran into a problem at https://tutor.openstax.org/course/5234 while using browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15.

The request details are:
get on https://tutor.openstax.org/api/courses/5234/dashboard returned status "504" with message "GATEWAY_TIMEOUT"
case 33562, course 5234, time 9:04pm
