### ISSUE TITLE
Highlight Icon doesn't show up when supposed to

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2510]
**SCENARIO** _Briefly describe the issue._
Highlight Icon doesn't show up when supposed to.
See the inconsistency between the two pictures attached below.
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_
Highlight Icon doesn't show up when supposed to when doing the homework as a student.
See the inconsistency between the two pictures attached below.
- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** teacher04
- **URL:**  https://tutor-qa.openstax.org/enroll/916584/Alicia-College-Physics-Spring-2019
- **Course number:**  
- **Course type:**  College Physics

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v ] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [ v] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
65.0.1
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)
![WechatIMG811.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/b8aed512-828a-4f83-bbf4-c955e4b160cb)
![WechatIMG805.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/11e44c60-d323-47d8-96d5-6c0a7088541e)

**Comment by carlycurran** [comment]
I think this is related to crowding in the toolbar, which may be fixed with Devika's new layout.

**Comment by nathanstitt** [comment]
this has been fixed somewhere along the line :-)

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
