### ISSUE TITLE
Baked books: Image Alignment Inconsistency- Content in Physics

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2512]
**SCENARIO** _Briefly describe the issue._

Images aligned in different ways- some in the center, others to the left
See screenshot:
(a)
this is the only case when one image is immediately followed by another image that is aligned differently
![WechatIMG817.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/681ad917-a41a-4f6a-8376-b0f4cbf07717)
(b)
A group of pictures aligned in the same way, followed by some text paragraphs, and then another set of pics aligned in the other way
![WechatIMG831.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/4c213132-5a54-4ec4-85a1-edad02279e62)
(c)
Suggestion:
 The cnx version got all the images aligned in the center, which looks great

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
65.0.1
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
