### ISSUE TITLE
Baked books: Chapter 34 rotated images-Content in Physics

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2516]
**SCENARIO** _Briefly describe the issue._
There are two images in Chapter 34 that have been rotated 90 degrees to the left:
![inv1.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/33040702-edf6-4809-9319-4130a7b620f4)
![inv2.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/35848d1b-3f74-4e1c-ba3a-8e8c7afa5218)
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
65.0.1
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by reedstrm** [comment]
This seems to be a content problem, the images are actually rotated on cnx.org, in the non-baked as well as baked. https://cnx.org/contents/jQSmhtXo@19.8:nU1oMkqE@7/34-6-High-Temperature-Superconductors
I've alerted the Books team, they've filed an errrata. Hi @oscryan !

<blockquote><div><strong><a href="https://cnx.org/contents/jQSmhtXo@19.8:nU1oMkqE@7/34-6-High-Temperature-Superconductors">OpenStax CNX</a></strong></div></blockquote>

**Comment by reedstrm** [comment]
Actually, it's all three images on that page that are rotated.  Moved to BLOCKED on content refresh

(Aside: it's best to have URLs _in addition_ to screenshots, so us devs can duplicate the problems and track down their cause.)

**Comment by oscryan** [comment]
I fixed them.

**Comment by Malar-Natarajan** [comment]
Verified in Qa

**Comment by Malar-Natarajan** [comment]
Issue with AP physics and is fixed in QA after reimport
