### ISSUE TITLE
Baked books: Chapter 32&33 table formatting -Content in Physics

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2518]
**SCENARIO** _Briefly describe the issue._

The tables in Chapter 32&33 have the following formatting issues:

(a) Indentation -weird space that preceeds the formulas:
![indnt4.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/95210e15-79bc-47f4-93bf-64eaed44487a)

![indnt3.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/e48979d1-ff88-4819-b445-110aa6b255a8)

![indnt2.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/fbb9b231-56e7-4629-ac06-e8344103d99f)

![indnt1.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/262afcd5-d91f-4b30-8f85-1610854cac93)

(b) Footnote -"9" should have been attached to the "B" in bold
![ft1.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/2e14716a-5df8-41d2-84d3-a44b4e5eb0c2)

(c) Alignment -the column name "kg" should match the column's position
![align1.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/2924eef2-abd7-4ff4-9bed-ea0dfb91f021)
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
65.0.1
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by CaptainXep** [comment]
3rd image on "a" and image "b" are still off. Everything else looks fine![Screen Shot 2019-05-14 at 9.22.52 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/91f8beaf-43cb-4153-8a13-5396506ed6ed)![Screen Shot 2019-05-14 at 9.23.27 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/c15c6ad4-7b46-4f3c-8f96-933aca94ab1c)

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
