### ISSUE TITLE
Baked books: Chapter 17: too many bars -Content in Physics

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2519]
**SCENARIO** _Briefly describe the issue._
See the screenshot below:

![baranswer.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/a1b5f71f-28db-4cd3-975e-2aebbc7f21f7)

A quick simple fix that I suggest is to turn “Answer” into a subtitle
-i.e. remove the bar that it has on

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
65.0.1
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by CaptainXep** [comment]
Student version of the physics textbook seems to be missing the "Applying to Science Practices" box.
QA version:
![Screen Shot 2019-05-14 at 10.32.22 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/2452f50a-5e3e-4e23-81b7-b0f2bc94786e)

Link:
https://tutor-qa.openstax.org/book/2559/section/8.7
(teacher04)

Original version:
![Screen Shot 2019-05-14 at 10.32.54 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/3289fba5-dc3a-4350-9333-069e4b96ba77)

**Comment by nathanstitt** [comment]
the course for https://tutor-qa.openstax.org/book/2559/section/8.7 is "college physics" not "AP Physics"

It looks like that course book simply lacks that section

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by CaptainXep** [comment]
Verified in Staging.
