### ISSUE TITLE
Baked books: Chapter Intro Size Unajustable -Content in Physics

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2520]
**SCENARIO** _Briefly describe the issue._

See the screen I got as the browser shrunk into this size:

![intro.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/3a1ac9f6-d62d-4cc4-870f-7fb6bd2b0910)

All the content below is adjusted automatically, except for the chapter introduction.

p.s. All chapters have this problem.
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
65.0.1
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by CaptainXep** [comment]
Verified in QA

**Comment by CaptainXep** [comment]
Verified in Staging

**Comment by itsgeraldwang** [comment]
Verified in Production.
