### ISSUE TITLE
Baked books: Chapter 4.4 [APLO 4.6] Not present in CNX verison-Content in AP Bio 

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2525]
**SCENARIO** _Briefly describe the issue._
As attached the screenshot:
![4.4.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/2f9229dc-6990-48fe-b4b2-0108dad5c910)
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [v] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [v] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
 72.0.3626.119
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by nathanstitt** [comment]
Hm, I see the same APLO text on both CNX and in the tutor content.  The text isn't surrounded by a tag so we can't really style it

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/3d269fd4-6e38-4876-8283-e325cb6f6655)


![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/216d4fb5-fdd3-410c-89fc-656f93ca57f1)

**Comment by CaptainXep** [comment]
Verified in QA

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
