### ISSUE TITLE
Baked books: Chapter3.3 Figure 3.14 too small -Content in AP Bio

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2526]
**SCENARIO** _Briefly describe the issue._
As attached the screenshot:
![3.14.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/3bb0b594-5dbc-4006-887d-dadbf8fef159)
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [v] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [v] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
 72.0.3626.119
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by nathanstitt** [comment]
Same cause as https://github.com/openstax/tutor-js/issues/2512 which was fixed in https://github.com/openstax/tutor-js/pull/2597


![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/349a23c6-9b1b-481c-acb2-9b21d6dfab5d)

**Comment by CaptainXep** [comment]
Verified in QA

**Comment by CaptainXep** [comment]
Verified in Staging

**Comment by itsgeraldwang** [comment]
Verified in Production.
