### ISSUE TITLE
Baked books: Too Many Layers at Chapter Endings? -Content in AP Bio

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2527]
**SCENARIO** _Briefly describe the issue._
As attached the screenshot:
![layer1.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/cf2392d4-5e1b-4fdb-a9f1-76c136581454)
![layer2.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/05f5ce76-7c4d-48c5-aaf1-adc56d7cde52)

Will it be better if we just align the title bars and just put the corresponding content below them?
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [v] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [v] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
 72.0.3626.119
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by brittany-johnson** [comment]
Note to self: AP Bio content on QA

**Comment by nathanstitt** [comment]
PR is https://github.com/openstax/tutor-js/pull/2551

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
