### ISSUE TITLE
Baked books: Duplicate Titles-Content in AP Bio

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2528]
**SCENARIO** _Briefly describe the issue._
As attached the screenshots:
![1.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/98c2a7aa-264e-4475-abcf-e913f27b0898)
![t2.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/92a7a496-6274-4a90-8f2e-f4330b345995)
![t3.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/c5715fe8-223f-495d-aec4-b251d187660a)
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [v] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [v] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
 72.0.3626.119
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
