### ISSUE TITLE
Baked books: Chapter 2.3 Font Size in Table 2.29 Appears to be Small-Content in AP Bio

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2529]
**SCENARIO** _Briefly describe the issue._
As attached the screenshot:
![2.3.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/2d6cbd39-1fcc-43fd-88ed-e60937edf4af)
I figured that students have to zoom-in in order to see the contents in the table, although the column names are more visible as compared.
*Note: Browsed in a full-screen.
---------------- 
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v] Tutor
- [ ] Payments
- [ ] Highlight 
- [v] Web

- **User Type:**
- [ ] Admin  
- [v] Content/QA
- [v] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v] content 
- [ ] demo
- **OS:**
- [v] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [v] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
 72.0.3626.119
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by nathanstitt** [comment]
that's an image so we can't really do much with it.  However with https://github.com/openstax/tutor-js/pull/2597 those images are a bit larger and centered:

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/a0d81a34-96e4-4cfb-9bf2-cf181d68c22b)

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.
