### ISSUE TITLE
Get SME Input After Regression Testing: AP Bio Question Prompts Need to be Modified from their Multiple Choice Versions

### ISSUE THREAD

**Issue by AliciaZong** [openstax/tutor-js#2566]
**SCENARIO** _Briefly describe the issue._
AP Bio Question Prompts Need to be Modified from their Multiple Choice Versions
Question IDs:
115@4 
190@4
114@6
119@5
--
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

115@4 
==
![WechatIMG1003.jpeg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/42016829-1506-456d-8023-dba1056763b6)
What does “these” refer to? it seems that there should have been a context
Is it asking the student to describe the production of the three chemicals?

Same issue with-
190@4
==
![10041555095179_.pic.jpg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/41981087-6fff-4c0c-9dd8-e73ebb5055d5)
114@6
==
![10051555095234_.pic.jpg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/698fe1f6-8594-4b85-8d1b-ed0a89a1b7c6)

Lastly,
119@5
==
![10061555097661_.pic_hd.jpg](https://images.zenhubusercontent.com/5c3d08cb1e45d50c0ed2aef8/520c4544-db47-490e-b5f4-bdbcb34e3ed2)
The prompt isn’t clear whether it’s about the difference in chemical structure or that in physical properties (which is the MC question asking about)

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [v ] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [v ] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** student03
- **URL:**  
- **Course number:**  
- **Course type:**  AP Bio

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [v ] content 
- [ ] demo
- **OS:**
- [v ] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [v ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  
66.0.2
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by openstaxalina** [comment]
115, 190, 114 - added "requires-choices" tag so that multiple choice distractors will display, without free response box.

119 - requires SME input.  See comments on https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor-js/2567.

**Comment by carlycurran** [comment]
@openstaxalina did you get SME input on 119, or do you think we should just leave it as-is?

**Comment by openstaxalina** [comment]
I created errata for 119: https://openstax.org/errata/9273

I am going to close this issue since we will track the errata in the errata tool.
