### ISSUE TITLE
Pulse Insights Tag Implementation

### ISSUE THREAD

**Issue by allisonhowell** [openstax/tutor-js#2634]
# Description
In order to launch Pulse Insights on OpenStax Tutor Bea, we need to place a code snippet on each page of the site.

# Acceptance
The code snippet provided by Pulse Insights is on each page of OpenStax Tutor Beta.

**Comment by allisonhowell** [comment]
PDF with directions and the code snippet below:

[https://app.zenhub.com/files/150612775/274fe4d9-a715-4516-b715-ac608e215340/download](https://app.zenhub.com/files/150612775/274fe4d9-a715-4516-b715-ac608e215340/download)

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>ZenHub unifies project management and development within GitHub.</div></blockquote>

**Comment by allisonhowell** [comment]
@carlycurran The attached pdf is what you'll need to put on your site so we can build the initial questions in Pulse Insights.

**Comment by carlycurran** [comment]
Talk to pulse insights - single page application - how do we handle single page app? Let's talk to Michael and Roy about their implementation

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
