### ISSUE TITLE
Scroll bar issue on the payments page

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/tutor-js#2735]
**SCENARIO** 
We had a student report that he was unable to pay because he could not use the scroll bar on the payments page. (He has paid now) So the student thought he couldn’t get to the credit card field to pay.

Tabitha logged in and was able to replicate this issue. She found that you can’t get to the entire form unless you scroll down with a rolling mouse or use the page down key. Normally, you can take your mouse and move the gray side bar up and down.....it won’t allow you to do that.

Cases 38754, 38755

Tabitha and the student were using Win 10 OS and Chrome

Link to slack conversation: https://openstax.slack.com/archives/C0F5MDAMC/p1568752404005800 
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [ ] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [ ] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [ ] content 
- [ ] demo
- **OS:**
- [ ] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by carlycurran** [comment]
Brooke to check this out @Brooke-Fail

**Comment by carlycurran** [comment]
Is there an issue when payment is already due and they are locked out?
Or choosing to pay early -- we could not replicate this case.

**Comment by Brooke-Fail** [comment]
I havent had any luck replicating this issue.
