### ISSUE TITLE
Change Help articles link to land on Tutor help articles

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/tutor-js#2753]
# Description
When you click on the Help articles from the Help drop down menu on Tutor, is there a way to automatically link to the Tutor search results? something like this: 
https://openstax.secure.force.com/help/pkb_home_2017?search=tutor

 ![2019-10-02_09-46-56.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/005337d3-fedc-467d-a84d-e3bbb57ab7d4)

Thank you for your help!   BBB
# Acceptance

**Comment by carlycurran** [comment]
yes, that's doable!

**Comment by nathanstitt** [comment]
sounds good, we'll use the link provided

**Comment by nathanstitt** [comment]
I'm not sure why the url given has `2017` in it but that seems like it might be old. 

That url was:
`https://openstax.secure.force.com/help/pkb_home_2017?search=tutor`

Using plain:
`https://openstax.secure.force.com/help?search=tutor`

Seems to give the same results and seems neater, so I'll use that unless anyone sees and issue with that.

**Comment by carlycurran** [comment]
sounds good -- thanks!

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
