### ISSUE TITLE
Assignment loading error for practice problems

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/tutor-js#2802]
**SCENARIO** 
 A student reached out saying that assignment loading for extra practice problems was failing saying "practice is not available" and then after about 7 times resubmitting the question would appear. I could not replicate when I logged into her account under "Practice my weakest topics?"

See screenshot below for error connected to 4.2 Newton's First Law of motion
[Screen Shot 2019-10-30 at 2.30.02 PM.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/dd6472ab-79a1-4567-85b3-9564a35b4ade)

Course number 5762, si: SG
CS case #40594
For reference, Slack channel link: https://openstax.slack.com/archives/C0F5MDAMC/p1572463595021800

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [ ] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [ ] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [ ] content 
- [ ] demo
- **OS:**
- [ ] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by Dantemss** [comment]
Seems like whenever I answer a question in a new section (that did not show in my PF before at all), then practice starts failing for a few minutes after that.

**Comment by Dantemss** [comment]
Hmm this student (tried to) create 104 practice tasks around the time of the CS report.
They seem to have eventually succeeded in creating 5 of them, since they answered 25 questions.

**Comment by bonnebbrown** [comment]
We had another report from course 5762 about this issue happening for Chapters 7&8.
"When I click on a section of practice problems, it takes a while to load problems and many times, gives me a message that no practice problems are available at this time. However, sometimes I will reload and they will come up, so I'm wondering what the problem is"

Using the safari browser, si:OS

CS case number 40794

**Comment by Dantemss** [comment]
https://github.com/openstax/biglearn-scheduler/pull/93 may improve this

**Comment by Brooke-Fail** [comment]
I havent seen this in testing but will test more in production, where the student got it to occur.

**Comment by Brooke-Fail** [comment]
Will create another card if biglearn has any issues again.
