### ISSUE TITLE
Excluded Question ID# 801@4 appears in reading assignment

### ISSUE THREAD

**Issue by khannum19** [openstax/tutor-js#2805]
**SCENARIO** _Briefly describe the issue._
Instructor: Jennifer Goninan
Course: 5499 (Bio-111D1 Fall 2019)
Homework: Chapter 11

Question ID # 801@4 is marked as excluded in the instructor's question bank but is showing up in student assignments.

 Here is the text of the question: Human males typically have XY chromosomes and females have XX chromosomes, but there are rare instances in which a male can inherit an XXY or an XYY, or a female can have three X chromosomes. Explain how an error in meiosis can cause these aberrations.

Case # 40639
Slack Link: https://openstax.slack.com/archives/C0F5MDAMC/p1572622354028500
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
- [ ] Accounts 
- [ ] BigLearn
- [ ] Exercises 
- [ ] CNX
- [ ] Tutor
- [ ] Payments
- [ ] Highlight 
- [ ] Web

- **User Type:**
- [ ] Admin  
- [ ] Content/QA
- [ ] Student  
- [ ] Teacher
- [ ] N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
- [ ] production 
- [ ] qa 
- [ ] staging
- [ ] dev 
- [ ] content 
- [ ] demo
- **OS:**
- [ ] Mac OSX 
- [ ] Windows
- [ ] Android 
- [ ] iOS
- **Browser:**
- [ ] Chrome 
- [ ] Firefox 
- [ ] Safari
- [ ] Opera 
- [ ] IE 
- [ ] Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by Dantemss** [comment]
This is another cloned course, same bug as the other one (fix is going out 2 weeks from Wednesday). I manually fixed existing courses but this assignment was published Sep 3rd, before the fix

**Comment by carlycurran** [comment]
This assignment was created before our fix was applied (created in September): cloned course issue
