### ISSUE TITLE
Update highlighter toolbar

### ISSUE THREAD

**Issue by jivey** [openstax/tutor-js#2819]
### Description 

Consolidate highlighter controls and assignment details into one toolbar.

![image.png](https://images.zenhubusercontent.com/5db706861484010001787b7f/e70e738f-ceea-4979-8cf5-ab8b947571aa)

![image.png](https://images.zenhubusercontent.com/5db706861484010001787b7f/e7849e1e-b6b2-4891-8aad-09edfb2683c4)

- [x] Breadcrumbs
- [x] Assignment details
- [x] Nav buttons with labels

----------------

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this bug.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
