### ISSUE TITLE
Convert highlighter view to modal

### ISSUE THREAD

**Issue by jivey** [openstax/tutor-js#2820]
### Description 

![image.png](https://images.zenhubusercontent.com/5db706861484010001787b7f/f01c1f4a-de12-4b5b-a818-69c60a77e0f5)

- [ ] No Filters message
- [ ] No highlights blank slate screen/message
- [ ] Clear button
----------------

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this bug.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
