### ISSUE TITLE
Update MultiSelect styles

### ISSUE THREAD

**Issue by jivey** [openstax/tutor-js#2821]
### Description 
Multi-select tool on highlights and notes modal ("Display Sections") tab  
- helper controls for selecting all or none
- dropdown no longer closes when you check a section
- multi-column layout depending on number of items
- scrolling enabled depending on number items 
- color changes (checkboxes have solid orange background with white check)

- [x] Color style
- [x] Scrolling view
- [x] Dynamic columns/sizing

----------------

### Acceptance criteria

- Dropdown remains open after making a selection
- Clicking the "all" link selects all items
- Clicking the "None" link deselects all items 
- When there are more than 20 item, items display in 2 columns
- when there are more than 40 items, the dropdown box scrolls

![Screen Shot 2019-11-22 at 4.06.06 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/1769d842-f5ac-4b25-87d6-4ea8f49eaf1b)

### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this story.

**Comment by carlycurran** [comment]
@jivey Looking good so far. I have a couple of questions on this: 

1. The first time I open the my highlights and no filter is selected, I don't see any message. I think the last screenshot above is what's supposed to happen in that case. This is what I see:
![Screen Shot 2019-11-26 at 12.31.53 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/69b8bb0c-3c7b-4a7e-a7f3-c6c361d49f90)

2. In this screenshot, when I select "none," the padding seems off: 
![Screen Shot 2019-11-26 at 12.32.02 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/6820d4cf-e4e1-454e-bd14-29c5f3d0d3ad)

cc @dkhowala not sure if you've seen the updates, but they're on tutor-qa.openstax.org now

**Comment by jivey** [comment]
@carlycurran I just pulled out the second screenshot from the description... this card only worked on things inside the dropdown (so I think the padding and no message has been like that?) But they are definitely being addressed with the current Modal work.

**Comment by carlycurran** [comment]
Ah, gotcha - thanks!

**Comment by Brooke-Fail** [comment]
Looks like the sections are being copied if the user creates more highlights in a section they have already viewed in the Highlights and Notes dashboard. 

https://drive.google.com/file/d/1aiW1FrIwitbnC7ytYgPmsGNPcUeGFRcX/view?usp=sharing

**Comment by Brooke-Fail** [comment]
There is also an issue with the sections list being scrolled up automatically in Chrome. 
<img width="1792" alt="Screen Shot 2019-11-26 at 3 24 47 PM" src="https://user-images.githubusercontent.com/48449285/69673904-0762a980-1061-11ea-9864-c5da89fe1940.png">

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging. There is another card to track the chrome issue mentioned above.

**Comment by Brooke-Fail** [comment]
Verified in Production.
