### ISSUE TITLE
Users without roles in a course should not be taken to dashboard

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-js#283]
I created a new user (without a course) and logged in and was taken to the Physics I dashboard, even tho he has no roles.

http://localhost:3001/api/courses.json

returns

```ruby
[
  {
    id: "1",
    name: "Physics I",
    roles: [ ]
  }
]
```

Where can we send these kind of anonymous users that will sign up but not be in a course?

**Comment by philschatz** [comment]
Ah, @darrenmason implemented this.

I'm not sure what it means to have no role in a course (until we decide on a way to apply for a course). Why isn't it just `[]` from the backend?

**Comment by darrenmason** [comment]
so we need to handle no role / no course?

**Comment by darrenmason** [comment]
I tried the above courses.json locally, it goes to /dashboard/  "no courses"

**Comment by Dantemss** [comment]
It shows up as "No courses." now. I think you can close.

**Comment by philschatz** [comment]
I think this is closed. If not, please reopen.
