### ISSUE TITLE
When there's only one catalog offering available, no preview courses are shown

### ISSUE THREAD

**Issue by reedstrm** [openstax/tutor-js#2908]
### Description 
When there's only one catalog offering available, no preview courses are shown. This occurs if there's literally only one catalog offering, or if there are two, but only one is marked available.

Corner case!

----------------

**Expected behavior:** 

Offer preview for single catalog offering

**Steps to Reproduce the issue:** 
mark all catalog offerings as not available, except for one.

----------------
### Acceptance Criteria
it works with one

### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this bug. 

----------------

- **Product:** - 
- **User Type:** - 
- **Username:** -
- **URL:** -
- **Course number:** -
- **Course type:** -

----------------
**Environment:**

- **Instance:** -
- **OS:** -
- **Browser:** -
- **Browser Version:** -

----------------
**Images or Screenshots** (_attach below_)

**Comment by reedstrm** [comment]
After debugging some with Roy and Josiah and Nathan and Dante, determined that the changes to MyCoursePreview to add an ExploreAPreview (tour) on the last preview course don't handle the case of there only being one preview correctly - since it strips off the last course and passes it as an `after`, the base course renderer fails to render since there are no non-tour-decorated previews to render (see: https://github.com/openstax/tutor-js/blob/b7290b9a565d16e14b40b671a9ec5232e90ccbb3/tutor/src/components/my-courses/listings.jsx#L220-L224 )

**Comment by nathanstitt** [comment]
This is no longer an issue now that we've re-designed the my-courses page

**Comment by Dantemss** [comment]
OBE due to my courses redesign.
