### ISSUE TITLE
Allow self-serve LMS integration

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor-js#2916]
### Description 
As an OpenStax instructor, I want to choose whether to enroll students through LMS or through enrollment links without going through customer support, so that I can manage my course on my own. 

As OpenStax, I want to offer this self-serve option to instructors for summer courses, so we can test how it works on a small population of users. 

All instructors, upon going to "course settings," should see the option to enroll via direct links or via LMS. The default checkbox selected should be direct links. 

### Acceptance Criteria

For all new courses created after the release, all instructors, upon going to "course settings," should see the option to enroll via direct links or via LMS. There is not a default checkbox selected. 

If an instructor has students enrolled, we show a message that instructor cannot choose LMS integration. IMPORTANT: Dropping students from course will not allow LMS integration. Teacher must re-create course. Do we have messaging for that, and is CS aware?

### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this change.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
