### ISSUE TITLE
Mobile and Tablet: Browse the book screen

### ISSUE THREAD

**Issue by camliu89** [openstax/tutor-js#3267]
- [x] The navbar is not collapsing to mobile state
- [x] There is empty space above the chapter 
- [x] The Notes modal should be fixed to the bottom of the screen and the styling is off, please refer to the invision screens. 
- [ ] Increase the contrast of the text in the notes modal. 
- [x] Move the big arrow to the prev and next button like in reading assignments. When a note is clicked hide the arrows, the caveat is that users will have to close the modal to navigate from the page. I think REX also does something similar. Can discuss if this is an issue. 
Note:  Some of the stuff isn't wrapping too well and creating weird horizontal score but I guess that would need more enquiry on the content front and we can do that later.

**Comment by nathanstitt** [comment]
@camliu89 does this still remains to be completed? or was it done in a different card?

**Comment by camliu89** [comment]
@nathanstitt yeah, I did not get a chance to work on this yet.

**Comment by Brooke-Fail** [comment]
This looks a lot better but there is still some cut off on the chapter menu especially on the teacher's view of browse the book.

Student:
<img width="569" alt="Screen Shot 2020-10-15 at 2 55 50 PM" src="https://user-images.githubusercontent.com/48449285/96179626-c7b1e400-0ef6-11eb-972a-c4b89e4f02d9.png">


Teacher:
<img width="569" alt="Screen Shot 2020-10-15 at 2 51 58 PM" src="https://user-images.githubusercontent.com/48449285/96179648-cf718880-0ef6-11eb-8090-4229b14775d9.png">

**Comment by Brooke-Fail** [comment]
Verified in QA and Staging. The issue mentions above is in a different card here https://github.com/openstax/tutor/issues/1386.

**Comment by Brooke-Fail** [comment]
Verified in Production.
