### ISSUE TITLE
With the release of Sheerid instantly verifying instructors, can we edit the messaging to get instantly verified by chat?

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/tutor-js#3301]
### Description 
Instructors (with the exception of international instructors) can get instantly verified via sheerid.  Can we change the messaging to let them know they may need to wait a few minutes for their permissions to update in the system?

**Scenario 1:** An instructor who is already faculty verified moves past this page and doesn't see a verification request. No problem here. 
**Scenario 2:** An instructor who has gone through SheerID but did not get immediate verification logs into Tutor and sees the waiting on verification page (below)
**Scenario 3:** An instructor who has gone through SheerID and DID get auto-verified OR an instructor who did not get auto-verified but provided docs to CS and is manually verified in SF sees this page because SF and accounts sync has not yet happened. **THIS IS THE PROBLEM** 

  ![Instant verification via tutor.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/6daf98f2-8e5a-45fb-b31c-b92dfd07056e)

There is some lag time between Salesforce, Accounts and Tutor, please see slack links: https://openstax.slack.com/archives/C0F5MDAMC/p1594932384347700?thread_ts=1594932219.346600&cid=C0F5MDAMC
https://openstax.slack.com/archives/C0F5MDAMC/p1594932602349900?thread_ts=1594932219.346600&cid=C0F5MDAMC
Thank you for your help. BBB

- When a teacher is verified through SheerID, it shows immediately in accounts. The teacher has immediate access to a PPT or solution manual behind the login wall. Why is Tutor different? 
- SheerID only works for brand new leads -- accounts sends SF a lead
- For existing accounts, the user goes through verification, they should be instantly verified in accounts, but sometimes shows up in SF as "pending"
- If user is at a school that SheerID doesn't have in their database, goes to CS
- Those who can't be verified by SheerID, user in pending state to upload docs. After 4 days, ends up in CS queue so we can deal with it. 

### Acceptance Criteria
- On the "Pending" page, Tutor FE asks accounts for updates on faculty verification status every minute. 
- Given that the FE will poll for updates on the page, If a user is on the page and verification comes through, page will automatically redirect to  MyCourses

**New page copy**
Header: "Almost ready!" 
Body: "If you received an email verifying your faculty status, we're gathering resources for your account. Check back in a few minutes."
 
Button text: "Chat Support"

### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this change.

**Comment by carlycurran** [comment]
now verified in accounts -- there is some lag time. We need to test that. 

@allisonhowell how long will SheerID take to verify an account? 

We will then update Tutor to check more often and change this langauge

**Comment by nathanstitt** [comment]
@mwharrison says:
 > It should be instant (like 20-30 seconds)… there are cases where they need to review docs that will take longer (like 1-8 hrs)
> but yes, 99% of the time under 5 minutes

**Comment by carlycurran** [comment]
@allisonhowell what message do you display to users if Sheer ID needs more input to verify them

**Comment by carlycurran** [comment]
instructor might be verified when they get to this page, but we're not updating the FE. 
**- So we would need to auto refresh the page every minute and tell them we're fetching the resources we need for your account. Should be ready soon.** 

This page comes up in two cases: 
- Verification is pending OR 
- FE hasn't synced yet 


If a user is verified before they leave accounts, we should see it, and the user should not come to this pending page. 

We need to test instant verification and see if users are getting this message. They should not be. 
- Start in Tutor, as a new user 
- Sign up as verified instructor (must get instantly verified) 
- Should _not_ see this page 
- If accounts sends you back to Tutor before SheerID responds, we can't do much but change our messaging.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
