### ISSUE TITLE
Add a location to the Question Authorship Terms of Use in the Instructor Getting Started Guide

### ISSUE THREAD

**Issue by bonnebbrown** [openstax/tutor-js#3614]
On page 11 of the [Instructor Getting Started Guide](https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/openstax_tutor_getting_started_guide_instructor.pdf), the Note refers to the Question Authorship Terms of Use, but doesn't tell the instructor where to find it. Is there a way to link the Terms of Use here, add a screenshot or let them know they will find them at the bottom of the page once they have clicked on a home work question in the Question Library? Thank you for your help. -BBB

[Question Authorship Terms of Use ISG.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/c13d1a17-d2ae-4b98-9242-ea8853ae29ce)

Case 63513

**Comment by nathanstitt** [comment]
Yes we can add a fixed url to view the terms and then give that to you for addition to the GSG.

**Comment by nathanstitt** [comment]
@dkhowala do you know how to edit the getting started guide to add this?

**Comment by dkhowala** [comment]
I Will add it to the GSG. We'll have to make some other updates to GSG as well. Will do all of it in one go. 

Okay if I move the card to Design? @nathanstitt

**Comment by nathanstitt** [comment]
sure, go for it!

**Comment by dkhowala** [comment]
Location added as well as drop question feature updated. 
New PDF location: https://drive.google.com/file/d/1kPR7riXsAmljGo99d7LvlBB4FPhw5X4t/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
