### ISSUE TITLE
New Questions created -Metabase

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3700]
As OpenStax I want to see information on questions that instructors are creating so that I can learn more about how they prefer to question their students.

By seeing how many instructors are using our Add Question" functionality, we can track how successful and useful a feature we've created, and also see the types of questions that instructors are creating for feedback to our question-creators.

__Acceptance Criteria:__
- Data to track will include which course a new question is being created for and what type of question (MC or WR) was created
- Visualization of date:
     - course on the X axis, number of questions on the Y axis and type of question as the color

**Comment by Dantemss** [comment]
https://metabase.openstax.org/question/78
