### ISSUE TITLE
Assignment Details Page info: Multiple Attempts

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3711]
As a student I want relevant information about my assignment on the assignment details page so that all important information to me is there when I begin.

Visual: https://www.figma.com/file/9DbIawVJXRPE0PqfBIvPCD/HI-Fi_v1?node-id=275%3A131

__AC:__
- To the existing assignment details page, add one more information item. 
__Feedback Time__ 
- Displayed, depending on the choice made by the instructor in the grading template:
  
Free response states:
- Immediately after graded
- After scores are published

Latework policy updates:
Updated screens here: https://invis.io/CGXT012V59T

__FOR TESTING__:
The primary button on this page updates based on the completion status of the assignment. 
Start - assignment not started
Continue - assignment started but not completed
Review - assignment completed (NOT affected by the assignment dates and grading status)
The header will continue to display the total available points on the top-right corner. 
Please ensure nothing breaks on the External assignment and Events details page. Existing behavior documentation: https://docs.google.com/document/d/1AmdT4cUk20R3LnVfCw0xlhT4oWKExMaqesJvC_JiKUQ/edit#heading=h.4bivwqit4yda

**Comment by Dantemss** [comment]
Looking at the logic for the button, the existing logic also changes the button to "Review" after the close date.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
