### ISSUE TITLE
403 error in course previews

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3718]

**Comment by BenjaminHolliday** [comment]
https://tutor.openstax.org/course/13688/task/3632172/step/64987902

Steps to reproduce:
- Go into the Physics preview course
- Got to gradebook
- Select an assignment by Hugo Jackson
- Click through the screens for the assignment and 403 error will appear as you advance
From Dante: "this assignment is previewstudent3's (hugo jackson) so you are not allowed to change it, but he is programmed to do it halfway. I think when you click the forward arrow the frontend is trying to complete that step of the reading and move on, which is not allowed... think it would happen on a real assignment too if the student did it halfway"

**Comment by Dantemss** [comment]
Bug currently needs to be reproduced on a real book, the mini ecosystem doesn't have enough chapters, so all the assignments in the preview course are already closed, which doesn't trigger the bug.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
