### ISSUE TITLE
Add Pardot tracking code to tutor.openstax.org

### ISSUE THREAD

**Issue by allisonhowell** [openstax/tutor-js#3754]
### User Story 
As a marketing automation admin, I want to add Pardot tracking code to tutor.openstax.org so that I can score prospects based on activity in Tutor, resulting in high quality leads for our sales team.

Tracking code for dev:

```
<script type="text/javascript">
piAId = '309222';
piCId = '1943';
piHostname = 'pi.demo.pardot.com';

(function() {
	function async_load(){
		var s = document.createElement('script'); s.type = 'text/javascript';
		s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
		var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent('onload', async_load); }
	else { window.addEventListener('load', async_load, false); }
})();
</script>
```

Tracking code for production: 

```
<script type=“text/javascript”>
piAId = ‘219812’;
piCId = ‘1120’;
piHostname = ‘pi.pardot.com’;
(function() {
	function async_load(){
		var s = document.createElement(‘script’); s.type = ‘text/javascript’;
		s.src = (‘https:’ == document.location.protocol ? ‘https://pi’ : ‘http://cdn’) + ‘.pardot.com/pd.js’;
		var c = document.getElementsByTagName(‘script’)[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent(‘onload’, async_load); }
	else { window.addEventListener(‘load’, async_load, false); }
})();
</script>
```

### Acceptance criteria
- Pardot tracking code is added to tutor.openstax.org and activity is visible on the prospect in Pardot

**Testing note:**
- BIT & Marcom can serve as primary testers for this work. Here is more about how to test the tracking code on your site: https://thespotforpardot.com/2020/05/21/how-to-test-in-pardot-sandboxes-training-orgs-and-even-production/ 
### Acceptance Tests for testrail
- **title**: 
- **categories**:

> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Tests that will be added or changed 
Written explanations of the tests that will have to be added or modified to test this story.

**Comment by allisonhowell** [comment]
<script type=“text/javascript”>
piAId = ‘219812’;
piCId = ‘1120’;
piHostname = ‘pi.pardot.com’;
(function() {
	function async_load(){
		var s = document.createElement(‘script’); s.type = ‘text/javascript’;
		s.src = (‘https:’ == document.location.protocol ? ‘https://pi’ : ‘http://cdn’) + ‘.pardot.com/pd.js’;
		var c = document.getElementsByTagName(‘script’)[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent(‘onload’, async_load); }
	else { window.addEventListener(‘load’, async_load, false); }
})();
</script>

**Comment by BenjaminHolliday** [comment]
Questions and resolutions: 

- Q: Do we want the same code snipped in all of our environments? 
A: That's ok.
- Q: Do we need any of the older pardot code?
A: All thats needed is the code snippet as defined above. Nothing else is required or being used.

**Comment by mwharrison** [comment]
Note: added a tracking code for dev, I believe the other one is for production. 
Probably need to make sure these can change per env:
```
piAId
piCId
piHostname
```

**Comment by mwharrison** [comment]
@jivey we've had a slight change to the tracking code after turning on a new feature in Pardot. Hopefully it's not too late for an update! Sorry!

```
<script type="text/javascript">
piAId = '309222';
piCId = '2313';
piHostname = 'pi.demo.pardot.com';

(function() {
	function async_load(){
		var s = document.createElement('script'); s.type = 'text/javascript';
		s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
		var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
	}
	if(window.attachEvent) { window.attachEvent('onload', async_load); }
	else { window.addEventListener('load', async_load, false); }
})();
</script>
```

**Comment by jivey** [comment]
@mwharrison Perfect timing actually, thanks!

**Comment by Brooke-Fail** [comment]
Will verify this in production, after it's released.

**Comment by Brooke-Fail** [comment]
Verified in Production
