### ISSUE TITLE
Enable Shuffle- Instructor View

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3772]
As a Tutor instructor I want to randomly shuffle the choices a student is offered in their Tutor assignment so that I can create assignments with more academic integrity.

Visual: https://www.figma.com/file/2ESAKAX4vckuZ54Cy1yrEk/Randomization?node-id=0%3A1

Note: Default for a new course will be shuffle. Cloned/copied courses should remain defaulted to not-shuffled if they were built before shuffle or if they originally built with not-shuffled chosen.

__AC:__
- An instructor can select if they want their students to see current answers randomized in a homework or reading grading template
- A pop up will explain to instructors what shuffling answers choices means if they hover and want to learn more
- Default for new grading template should be "yes" , that is shuffle is chosen by default. 
- Available in Reading and HW assignments

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
