### ISSUE TITLE
Submission overview view

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3773]
As an instructor I want a clear understanding of what I'm viewing in the gradebook now that shuffle is an option so that I am not confused when looking at answers.

Visual: https://www.figma.com/file/2ESAKAX4vckuZ54Cy1yrEk/?node-id=4%3A1880

__AC:__
- The submission overview page does not change functionally.
- Conditional- if the assignment has a grading template where shuffle has been enabled then show the message. If shuffle not enabled- do not show.
- Messaging informs an instructor that student may see answers in a different order than presented on the overview. 
   - Add a note with an info icon. below the summary table on both RDs and HWs
Hovering over the info icon shows a tip.’This page shows questions and answers in the same order as when the assignment was built. Answer choice order may have been randomized for students. Responses are summarized by student answer choice.’ 

- Choices are displayed based on the order they were presented during the set up of the assignment.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
