### ISSUE TITLE
Lock answer choice- create Question editor

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3780]
As a question creator I want to be able to lock the order of my created questions and not have shuffle mess it up so that I can create questions and choices that make sense to students.

VIsual: https://www.figma.com/file/2ESAKAX4vckuZ54Cy1yrEk/?node-id=103%3A100

__AC:__
- In the question creation screen, give an option to lock the choices for the created question. If this option is checked for any question (tutor or user generated), DO NOT shuffle the choice order. 
- Locking an answer choice always displays the choices in the order they were created.
- Selecting the checkbox is NOT mandatory.
- Users can click on the infotip icon to learn more about the feature. 

Infotip popup content: Answer choices on a question may be shuffled (students get the same questions but different order of choices).   Select Lock answer choices order when the order is critical and should NOT be shuffled. Example: questions with ‘All/None of the above’ or ‘both a and b’ as answer choices. 

- For questions that already exist, then the default answer order will default to locked.

- DO NOT shuffle choices if there are only two answer-choices available on a question. If there are only two options the checkbox should be in active-disable state.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
