### ISSUE TITLE
Change explanation for multiple attempts

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3787]
As an instructor I want a clearer explanation of multiple attempts so that I have better understanding of the feature.

__AC:__
- Wording on the tool tip on the grading template should change to the simplified version displayed here: ![Screen Shot 2021-09-29 at 11.00.41 AM.png](https://images.zenhubusercontent.com/60d1f363caf077e11b920424/42ea0f6b-8345-4ae0-b103-865c11d87f48)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
