### ISSUE TITLE
Add American Government to Tutor

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3795]
Task break down...what else?:
Add Book content
Introduction of new book announcement
Add icon
SIte announcement
Add reading instructions?

**Comment by dkhowala** [comment]
The light blue is correct but white doesn't pass AA on it. We just take the base of the book color and the text is in accordance with the color combination I shared during the 'My courses' project.

**Comment by Brooke-Fail** [comment]
Verified in QA.
