### ISSUE TITLE
Shuffle- student view

### ISSUE THREAD

**Issue by BenjaminHolliday** [openstax/tutor-js#3803]
_AC:__
- If shuffle has been selected by the instructor, the student will see a randomized order of choices.
- Exceptions will be UNLESS the question is marked as ‘order is important’(Tutor questions)  __or__ ‘Locked choice order’
__OR__ has only two answer-choices available. 
- Once a student attempts a questions, we will not shuffle the order once it has been attempted.
- We will __not __shuffle in between multiple attempts
- If a student encounters a question, leaves, and then comes back, the shuffle function should randomize as if this is the first time the student encountered the question. 

__Notes:__ Shuffle on load

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
