### ISSUE TITLE
Data request and metabase access

### ISSUE THREAD

**Issue by debshila** [openstax/tutor-js#3843]
Hello,

Thanks for your help. Here are 2 tables that we need for a project. 
Question x student
- Question related: exercise_id, part number, stem, response options, correct answer, book/chapter/section, course, free vs. 2-step response,  tags
- student related: research_id, response, timestamp, points achieved, out of total points, 

Highlights and notes for each student
- student highlights and notes

Can you please share this metabase view with Rich's student, Shashank Sonkar (ss164@rice.edu)?

**Comment by Dantemss** [comment]
https://metabase.openstax.org/question/85-student-answers?Year=2022&Term=2&MinStudents=2
https://metabase.openstax.org/question/86-student-highlights-and-notes?Year=2022&Term=2&MinStudents=2

**Comment by debshila** [comment]
Thanks for all your help with this, Dante!!!
