### ISSUE TITLE
"Cancel" button in the HW builder takes the teacher back to the course selection screen

### ISSUE THREAD

**Issue by Dantemss** [openstax/tutor-js#465]
Should this be? Going back to the calendar would seem more intuitive to me.

**Comment by Fredasaurus** [comment]
+1

**Comment by philschatz** [comment]
Yep, there was an assumption that there was only 1 course (so going to the dashboard was fine).

Adding @jivewise to this

**Comment by jivewise** [comment]
Ah, yes, I'll get start a PR for this shortly.

**Comment by jivewise** [comment]
Should be done here: https://github.com/openstax/tutor-js/pull/486

**Comment by Fredasaurus** [comment]
Should be back to calendar.
