### ISSUE TITLE
Display error messages to users when 500's occur

### ISSUE THREAD

**Issue by jpslav** [openstax/tutor-js#560]
Pop up a modal (or similar) for when a 500 error occurs, with standard "An error occurred" messaging, the returned error_id, and a help desk link?  We're going to be 500'ing if the practice widget ends up being empty (which has happened and shouldn't be happening), and it'd be nice if the 500 showed up in more than just the console.

**Comment by philschatz** [comment]
Added #566 to track progress on this feature
