### ISSUE TITLE
422 sometimes when choosing multiple choice answer

### ISSUE THREAD

**Issue by pandafulmanda** [openstax/tutor-js#751]
The issue this fixes is hard to reproduce.  Steps are:

1. Answer a free response
1. Choose a multiple choice answer
  * Must be while free response is still saving/while we have not received a response back from the server
1. A response similar to: 
  ```{"status":422,"errors":[{"code":"free_response_is_required","message":"Free response is required"}]}```
  is received

![422error](https://cloud.githubusercontent.com/assets/2483873/9964095/13879726-5df4-11e5-8f1d-f2ad29661cb9.PNG)

**Comment by Dantemss** [comment]
I support fixing this quickly since we don't even get emails about 422's.

**Comment by philschatz** [comment]
merged!
