### ISSUE TITLE
Self-hosting Fonts?

### ISSUE THREAD

**Issue by philschatz** [openstax/tutor-js#86]
It may be worthwhile to all fonts locally (or all remotely). This stems from #85.

Some links from @Fredasaurus:

- http://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server
- http://michaelboeke.com/blog/2013/09/10/Self-hosting-Google-web-fonts/

We decided to use the MathJax CDN (@lakshmivyas) and maybe some discussion should be had on CSS fonts.

**Comment by lakshmivyas** [comment]
@philschatz - I will vote for using a public CDN for fonts and css as long as the host is reliable.  Reasons are very similar to our mathjax discussion.

**Comment by dak** [comment]
It should be possible to do both, using the CDN as the preferred source and a locally served version as a backup.  Just list multiple `src` elements for the font-face.

**Comment by philschatz** [comment]
Closing this since we are hosting all the fonts ourselves
