### ISSUE TITLE
Reduce Technical Debt

### ISSUE THREAD

**Issue by philschatz** [openstax/tutor-js#919]
# Upgrade Dependencies
- [ ] `react`
  - [ ] [`react-router@1.0`](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v1.0.0.md)
    - we can do dynamic chunks really easily: https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md
    - uses `history` package instead of `Navigation`
  - [x] `react-bootstrap`
    - OverlayTrigger: https://github.com/react-bootstrap/react-bootstrap/pull/855
    - trigger='manual' removed
    - NavBrand formatting
    - DropdownMenu, MenuItem update jsx format / props
  - [ ] `fixed-data-table`
  - [ ] `react-calendar`
- [x] standardize selenium helper names
- [x] remove jQuery
- [ ] update `phantomjs` to 2.x
- [ ] replace `underscore` with `lodash`
- [x] upgrade time stuffs -- #1055 
  - `moment`
  - `twix`
  - `react-datepicker`
# Refactor Code
- [ ] use `classnames`
- [ ] remove `bootstrap-material-design`
- [ ] remove lint warnings from cjsx files
- [ ] `moment`
- [ ] increase code coverage
- [ ] replace flux
- [ ] ES6?!?!?!?!??!?!?!

**Comment by pandafulmanda** [comment]
does this mean, `react@0.14` as well?

**Comment by philschatz** [comment]
ah yep; added. Feel free to add more to the list :smile:

**Comment by philschatz** [comment]
Example of upgrading `react`, `react-router`, and `react-bootstrap`: https://github.com/philschatz/gh-board/compare/2b12616...4bcf49

**Comment by pandafulmanda** [comment]
might removing dependency on `jQuery` be something we do as part of this?

**Comment by nathanstitt** [comment]
I agree, would be nice to remove jQuery.  @philschatz I think you mentioned at one time that you know of or had written a plain xhr alternative ?

**Comment by pandafulmanda** [comment]
i liked when we used [axios](https://github.com/mzabriskie/axios) in openstax/concept-coach but that depended on promises :(

**Comment by pandafulmanda** [comment]
would having a style guide be a part of this?

**Comment by philschatz** [comment]
Yep, added `jQuery` to the list! The "plain xhr alternative" is at [octokat.js/src/request.coffee](https://github.com/philschatz/octokat.js/blob/master/src/request.coffee#L12-L43)
