### ISSUE TITLE
How best to write selenium helpers

### ISSUE THREAD

**Issue by nathanstitt** [openstax/tutor-js#951]
Writing this as an issue vs a napkin note so so people can comment.

We can write selenium helpers as objects, or as a collection of structured functions.

An simplified version of an object oriented helper would be something like:

```coffee

class ProgressGuide extends PanelElement
  constructor: (test) ->
    @element = test.driver.findElement(css: '.student-dashbaord')

  getTitle: ->
    @element.findElement(css: '.title').then (el) ->
      el.getText()

class StudentDashboard
  constructor: (test) ->
    @element = test.driver.findElement(css: '.student-dashbaord')

  getProgressGuide: ->
    new Promise (resolve, reject) =>
      @element.findElement(css: '.progress-guide').then (el) =>
        resolve(new ProgressGuide(@test, el))

module.exports = StudentDashboard
```

To use this in a spec you could:

```coffee
StudentDashboard = require 'helpers/student-dashboard'

@it 'has the proper title', ->
    dash = new StudentDashboard(@)
    dash.getProgressGuide().then (guide) ->
      guide.getTitle().then (title) ->
        expect(title).to.equal('Progress Guide')
```

As you can see, the object oriented helper yields different things from it's promises. `StudentDashboard.getProgressGuide()` yields an instance of a `ProgressGuide` object, while the promise returned by `getTitle` yields a string.

Phil suggested we could employ a different method that might be less confusing.   In his suggestion, each getter method would return a selenium element object. That way there would be no confusion over what a helper would yield.

Code written in that manner would look more like:

```coffee

getProgressGuide = (test) ->
  test.driver.findElement(css: '.student-dashbaord')

ProgressGuide =
  getTitle: (el) ->
    @element.findElement(css: '.title')



module.exports = {getProgressGuide, ProgressGuide}

```

and could be used as:

```coffee
StudentDashboard = require 'helpers/student-dashboard'

@it 'has the proper title', ->
  StudentDashboard.getProgressGuide(@).then (guideEl) ->
    StudentDashboard.ProgressGuide.getTitle(guideEl).then (title) ->
      title.getText().then (title) -> # <- title is an Element, getText is selenium
        expect(title).to.equal('Progress Guide')
```

Thoughts on the two approaches?  @philschatz if I've misrepresented your approach please correct me

refs #931

**Comment by pandafulmanda** [comment]
i think the object oriented version means that when we use that to write out tests, it follows the default selenium paradigm.  I am fiddling with something like this:

```
class TestElement extends selenium.WebElement
```

such that when you have a `testElement` you can do, `testElement.findElement` etc.

**Comment by philschatz** [comment]
I guess I hadn't thought of OO before, but after looking at the option a bit here were a few concerns we could figure out?

- state
- documentation
- selenium versioning

# State

Given that the selenium objects are _very_ temporal (if you `findElement`, change the page, change back, and then try to use the element it will be stale) I was suggesting that all state be in the test, not the objects created as part of the test. Having objects, would make it attractive to add state in)

# Documentation

- It _seems_ like having additional objects that return custom objects makes it less clear where to look up documentation
- If we extend objects it becomes less clear:
  - what methods are available
  - what kind of object is returned

To the last point, one may need to write a test that does `.findElements('.task')` which yields an array of `WebElement` but `dashboard.getTasks()` yields a `Task` element that extends `WebElement`

# Selenium Versioning

- I'm not sure how much services like BrowserStack or Sauce replace Selenium libs when running
- How closely would we be bound 
- `.`-completion would be annoying (not sure if anyone else does this)

**Comment by pandafulmanda** [comment]
@philschatz you make a good point about the state thing and after playing around with extending the WebElement i think my earlier idea suffers from some problems...I'm still trying some different things and don't have anything concrete yet.  With trying to extend the WebElement, I was hoping to address when QA comes in to write tests, then they dont have to learn our functions that we've made for our helpers, on top of knowing the selenium ones

**Comment by pandafulmanda** [comment]
https://github.com/openstax/tutor-js/blob/865f61f09c7478533318296de247cf300e38d693/test-integration/helpers/test-element.coffee

**Comment by jivewise** [comment]
I'm partial to what @pandafulmanda suggested, if we are writing the tests ourselves.

If QA is going to be writing the tests, then I think it'd be helpful to limit the amount of chaining that we need to do, even if they are copying/pasting things around.  I think it's easier to document verbose function arguments.

On another note, I really like the idea of pulling out all of our selectors out into a common area.

**Comment by philschatz** [comment]
Implemented these suggestions in #953

**Comment by philschatz** [comment]
Maybe we could convert the conclusions in here into the `README` in the `./test-integration` dir?

**Comment by pandafulmanda** [comment]
okay, working on some documentation now

**Comment by philschatz** [comment]
closing this since I think it's mostly been decided and #965 has a link to this
