### ISSUE TITLE
Remove media preview image fix when Firefox 46 is released.

### ISSUE THREAD

**Issue by pandafulmanda** [openstax/tutor-js#977]
When [Firefox 46 is released](https://wiki.mozilla.org/RapidRelease/Calendar), the JavaScript based [`setMaxImageWidth`](https://github.com/openstax/tutor-js/pull/974/files#diff-95a1a8c177e307ecd56713813a6e14f6R58) fix from #974 should be removed.

## Details
Image `max-width` was not working in [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=975632). 

## Update
*02/10/2016*

While the Firefox bug has been marked as RESOLVED, you can still see it's currently an issue in Firefox `44.01` in [this JS Fiddle](https://jsfiddle.net/b8afdtgt/3/).  Based on [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=823483) linked in [this comment for the 975632](https://bugzilla.mozilla.org/show_bug.cgi?id=975632#c35), the fix will be released in Firefox `46`, slated for release [April 19th](https://wiki.mozilla.org/RapidRelease/Calendar). Based on a quick test on [Nightly](https://www.mozilla.org/en-US/firefox/channel/#developer) which is at `46.0a2`, the bug is indeed fixed.

## 44.01
![screen shot 2016-02-10 at 3 32 59 pm](https://cloud.githubusercontent.com/assets/2483873/12962572/a3bc9448-d00b-11e5-914b-01134edd39cb.png)

![screen shot 2016-02-10 at 3 37 32 pm](https://cloud.githubusercontent.com/assets/2483873/12962731/49fc0834-d00c-11e5-8db3-579ae93155c6.png)

## 46.0a2
![screen shot 2016-02-10 at 3 34 24 pm](https://cloud.githubusercontent.com/assets/2483873/12962603/ca1d75da-d00b-11e5-939b-1a3d08b6e06a.png)

![screen shot 2016-02-10 at 3 37 41 pm](https://cloud.githubusercontent.com/assets/2483873/12962735/5120b7c2-d00c-11e5-8836-17ee3fc0e7d6.png)

**Comment by philschatz** [comment]
Fixed in #974

**Comment by pandafulmanda** [comment]
This is not fixed by #974, this is here as a reminder to remove the `setMaxImageWidth` hack once Firefox 46 is released

**Comment by philschatz** [comment]
oh I see... I missed the 1st word in the title :blush:
