### ISSUE TITLE
How to bring test-integration into the test-automation

### ISSUE THREAD

**Issue by pandafulmanda** [openstax/tutor-js#994]
How do we bring the `test-integration` into the [test-automation](https://github.com/openstax/test-automation) project?

Concerns are:
* Keeping the repo relatively clean and hopefully free of having to include all of `tutor-js`
* Tangentially related -- how do we decrease the amount of processing/building we would run on Sauce Labs

We are keeping in mind that `test-automation` needs to be easily configurable to test both remotely (for QA) and locally (for development).

# Current ideas
* use `pip`
* use `npm`
* Git subtree, submodules, or bash
* Build and host helpers separately
* Include all of `tutor-js`

### Why
`test-automation` is currently mostly a Python repo
### Why not
However, that will not be the case in the future, as tests will be written in some form of JS.  The planis for current Python code to be pulled out to a package and the Python code will be used as command-line scripts.

### Why?
Tests will be in JS so loading with npm will make it very easy to load in the necessary helpers without additional work.  Also, npm will be part of the workflow anyway.
### Why not?
Installing the whole repo into test-automation is a bit excessive.  This would add time for Sauce Labs when installing and building tests.  However, []() would handle this nicely.

If module size remains a concern, finding ways to install the specific folder (pulling out test-integration into a separate repo) could work, but would likely add additional overhead for maintenance.

### Why?
Pulls in just the parts needed
### Why not?
Involves writing an extra script that is likely [to be complicated and require maintenance](http://stackoverflow.com/questions/23937436/add-subdirectory-of-remote-repo-with-git-subtree#answer-30386041).

### Why?
Less for `test-automation` to pull in, there will be no extra files locally.
### Why not?
Maintenance overhead, need to do some extra steps to load in remote JS, uptime of JS file becomes crucial, adds debugging difficulties

### Why?
Regardless of how, you can avoid the size problem and send only the built and minified JS to Sauce Labs.
### Why not?
Extraneous files when working locally

# Suggestions?
Any other ideas?  We are not looking for a final decision, just ideas and potential pros/cons before we start trying some things.

/cc @openstax/tutor-fe @openstax/test

**Comment by philschatz** [comment]
I am not familiar with saucelabs process for running tests when combined with Jenkins. From how [Travis recommends using SauceLabs](https://docs.travis-ci.com/user/sauce-connect/) it seems Jenkins could control the Sauce browser without having to send files over. If that is the case, would it reduce the concern about the repository size? Also, could Jenkins also run the developer Selenium tests?

**Comment by philschatz** [comment]
Has this work been concluded? /cc @openstax/test

**Comment by philschatz** [comment]
assuming it's been concluded
